name: ecommerce-server CI/CD

on:
  push:
    branches: [master, develop]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: set up nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: checkout code
        uses: actions/checkout@v2

      - name: get npm cache
        id: npm-cache-dir
        run: echo "::set-output name=dir::$(npm config get cache)"

      - name: set up cache
        uses: actions/cache@v1
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: npm install
        run: npm ci
        env:
          CI: true

      - name: run lint
        run: npm run lint

      - name: build docker image
        run: docker build . -t ljaks/ecommerce-server:1.0

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push to dockerhub
        run: docker push ljaks/ecommerce-server:1.0

      - name: login to heroku
        run: heroku container:login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

      - name: push to heroku
        run: heroku container:push -a ecommerce-server web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}

      - name: release the image
        run: heroku container:release -a ecommerce-server web
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_TOKEN }}
